// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLTIxYszgUBX9inRgAp8e9X6oURk05IB4',
    appId: '1:729460781433:web:2ec833b5daed29022a7fa8',
    messagingSenderId: '729460781433',
    projectId: 'comments-app-d8b3e',
    authDomain: 'comments-app-d8b3e.firebaseapp.com',
    storageBucket: 'comments-app-d8b3e.appspot.com',
    measurementId: 'G-WHRE6MFNR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKdrx-MWHEdtVLAL9mgyRcRXuEN2OzJH0',
    appId: '1:729460781433:android:9d5f5b58a5d637b92a7fa8',
    messagingSenderId: '729460781433',
    projectId: 'comments-app-d8b3e',
    storageBucket: 'comments-app-d8b3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOHEsl5KAdoijvxBTrTPUnEY1eI8asr2A',
    appId: '1:729460781433:ios:b46ab5a0e99b329e2a7fa8',
    messagingSenderId: '729460781433',
    projectId: 'comments-app-d8b3e',
    storageBucket: 'comments-app-d8b3e.appspot.com',
    iosBundleId: 'com.example.commentsApp',
  );
}
